[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# CMS admin must serve its own index
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
