backend:
  name: github
  repo: fniemczewski2/fundacjazaplon
  branch: main
  api_root: "/.netlify/functions/gh"

publish_mode: editorial_workflow

media_folder: "public/images"
public_folder: "/images"

locale: 'pl'

collections:
  - name: "settings"
    label: "Ustawienia"
    files:
      - file: "content/settings/site.json"
        label: "Strona – ustawienia"
        name: "site"
        fields:
          - { label: "Nazwa organizacji", name: "name", widget: "string" }
          - { label: "Opis (tagline)", name: "tagline", widget: "string", required: false }
          - { label: "Logo (jasne)", name: "logo", widget: "image", required: false }
          - { label: "Logo (ciemne)", name: "logoDark", widget: "image", required: false }
          - label: "Kolory (H S% L%)"
            name: "colors"
            widget: "object"
            fields:
              - { label: "Brand",  name: "brand",  widget: "string", default: "208 63% 27%" }
              - { label: "Base 100", name: "base100", widget: "string", default: "30 30% 98%" }
              - { label: "Base 200", name: "base200", widget: "string", default: "48 100% 86%" }
              - { label: "Text",    name: "text",    widget: "string", default: "0 0% 21%" }

  - name: "team"
    label: "Zespół/Zarząd"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Imię i nazwisko", name: "name", widget: "string" }
      - { label: "Rola", name: "role", widget: "string" }
      - { label: "Zdjęcie", name: "avatar", widget: "image", required: false }
      - { label: "Bio", name: "bio", widget: "text", required: false }
      - { label: "Kolejność", name: "order", widget: "number", value_type: "int", min: 1, default: 1 }
      - { label: "Publikuj?", name: "published", widget: "boolean", default: true }

  - name: "projects"
    label: "Projekty"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Miniatura", name: "cover", widget: "image", required: false }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: "Tagi", name: "tags", widget: "list", required: false }
      - { label: "Publikuj?", name: "published", widget: "boolean", default: true }

  - name: "posts"
    label: "Aktualności/Blog"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Obraz", name: "cover", widget: "image", required: false }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: "Publikuj?", name: "published", widget: "boolean", default: true }
